#
# development configuration
#
mybatis:
   config-location: classpath:mybatis/configuration.xml
   
spring:
   devtools:
      livereload:
         enabled: true
      datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://34.64.199.56:5432/poscoict?characterEncoding=UTF-8&serverTimezone=UTC
      username: poscoict
      password: 1234

eureka:
   instance:
      preferIpAddress: true
   client:
      fetchRegistry: true
      registerWithEureka: true
      serviceUrl:
         defaultZone: http://localhost:8762/eureka
logging:
   pattern:
      console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{5} - %msg%n"
   level:
      root: INFO   